# Generated by Django 5.2.17 on 2026-10-03 06:49

import apps.content.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(max_length=500, verbose_name="Nomi (uz)"),
                ),
                (
                    "title_kr",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Nomi (kr)"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Nomi (ru)"
                    ),
                ),
                (
                    "info_uz",
                    models.TextField(blank=True, verbose_name="Ma'lumot matni (uz)"),
                ),
                (
                    "info_kr",
                    models.TextField(blank=True, verbose_name="Ma'lumot matni (kr)"),
                ),
                (
                    "info_ru",
                    models.TextField(blank=True, verbose_name="Ma'lumot matni (ru)"),
                ),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        upload_to=apps.content.models.upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "webp", "gif", "svg"]
                            )
                        ],
                        verbose_name="Belgi rasmi",
                    ),
                ),
                (
                    "info_image",
                    models.FileField(
                        blank=True,
                        upload_to=apps.content.models.upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "webp", "gif", "svg"]
                            )
                        ],
                        verbose_name="Ma'lumot rasmi",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
            ],
            options={
                "verbose_name": "Bo'lim",
                "verbose_name_plural": "Bo'limlar",
                "ordering": ["stage__number", "order", "id"],
            },
            bases=(apps.content.models.I18nMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(unique=True, verbose_name="Raqam"),
                ),
                (
                    "title_uz",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Nomi (uz)"
                    ),
                ),
                (
                    "title_kr",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Nomi (kr)"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Nomi (ru)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bosqich",
                "verbose_name_plural": "Bosqichlar",
                "ordering": ["number"],
            },
            bases=(apps.content.models.I18nMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_uz", models.TextField(verbose_name="Savol (uz)")),
                ("text_kr", models.TextField(blank=True, verbose_name="Savol (kr)")),
                ("text_ru", models.TextField(blank=True, verbose_name="Savol (ru)")),
                (
                    "explanation_uz",
                    models.TextField(blank=True, verbose_name="Izoh (uz)"),
                ),
                (
                    "explanation_kr",
                    models.TextField(blank=True, verbose_name="Izoh (kr)"),
                ),
                (
                    "explanation_ru",
                    models.TextField(blank=True, verbose_name="Izoh (ru)"),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        upload_to=apps.content.models.upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "webp", "gif", "svg"]
                            )
                        ],
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "photo_hint",
                    models.FileField(
                        blank=True,
                        upload_to=apps.content.models.upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "webp", "gif", "svg"]
                            )
                        ],
                        verbose_name="Photo izoh",
                    ),
                ),
                (
                    "audio_hint",
                    models.FileField(
                        blank=True,
                        upload_to=apps.content.models.upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp3", "ogg", "m4a", "wav"]
                            )
                        ],
                        verbose_name="Audio izoh",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Nashr etilgan"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="content.category",
                        verbose_name="Bo'lim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savol",
                "verbose_name_plural": "Savollar",
                "ordering": ["category", "order", "id"],
            },
            bases=(apps.content.models.I18nMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_uz", models.TextField(verbose_name="Javob (uz)")),
                ("text_kr", models.TextField(blank=True, verbose_name="Javob (kr)")),
                ("text_ru", models.TextField(blank=True, verbose_name="Javob (ru)")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="To'g'ri"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Tartib"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="content.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Javob",
                "verbose_name_plural": "Javoblar",
                "ordering": ["order", "id"],
            },
            bases=(apps.content.models.I18nMixin, models.Model),
        ),
        migrations.AddField(
            model_name="category",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="content.stage",
                verbose_name="Bosqich",
            ),
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="Raqam")),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="content.stage",
                        verbose_name="Bosqich",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variant",
                "verbose_name_plural": "Variantlar",
                "ordering": ["stage__number", "number"],
            },
        ),
        migrations.CreateModel(
            name="VariantQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.question",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.variant",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("variant", "question")},
            },
        ),
        migrations.AddField(
            model_name="variant",
            name="questions",
            field=models.ManyToManyField(
                related_name="variants",
                through="content.VariantQuestion",
                to="content.question",
            ),
        ),
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.UniqueConstraint(
                fields=("stage", "number"), name="uniq_stage_variant"
            ),
        ),
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stage__isnull", True)),
                fields=("number",),
                name="uniq_general_variant",
            ),
        ),
    ]
