# Generated by Django 5.2.17 on 2026-10-03 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("study", "Ta'lim (bo'lim)"),
                            ("category", "Qism bo'yicha test"),
                            ("stage", "Bosqichli test"),
                            ("final", "Yakuniy test"),
                            ("variant", "Test varianti"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ref_id", models.PositiveIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total", models.PositiveSmallIntegerField(default=0)),
                ("correct", models.PositiveSmallIntegerField(default=0)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Urinish",
                "verbose_name_plural": "Urinishlar",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AttemptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("answer_order", models.JSONField(default=list)),
                ("is_correct", models.BooleanField(null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="exams.attempt",
                    ),
                ),
                (
                    "chosen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.answer",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.question",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("attempt", "position"), ("attempt", "question")},
            },
        ),
    ]
