# Generated by Django 5.2.17 on 2026-10-03 06:49

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoginFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="F.I.Sh.")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "code_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "code_hint",
                    models.CharField(
                        editable=False,
                        max_length=8,
                        verbose_name="Kod (oxirgi 4 belgi)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Amal qilish muddati"
                    ),
                ),
                (
                    "max_devices",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Qurilmalar soni"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "O'quvchi",
                "verbose_name_plural": "O'quvchilar",
            },
        ),
        migrations.CreateModel(
            name="DeviceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sid",
                    models.CharField(
                        default=apps.accounts.models.new_sid,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("device_id", models.CharField(max_length=64)),
                ("wrapped_key", models.BinaryField()),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qurilma sessiyasi",
                "verbose_name_plural": "Qurilma sessiyalari",
                "indexes": [
                    models.Index(
                        fields=["student", "revoked"],
                        name="accounts_de_student_34fd97_idx",
                    )
                ],
            },
        ),
    ]
